version: '3.9'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8060:8060"
    depends_on:
      - "db"
    links:
      - "db:database"
  
  db: 
    image: "mysql:latest"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 