CREATE TABLE IF NOT EXISTS users (
    user_id     VARCHAR(255) PRIMARY KEY,
    fullname    VARCHAR(150) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) Engine = InnoDB
